spring.application.name=webshop-product-service
server.port=8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/auth/jwks
spring.jpa.hibernate.ddl-auto=update
server.forward-headers-strategy=framework